name: Deploy 1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            export NVM_DIR=~/root/.nvm
            source ~/.nvm/nvm.sh
            cd /home/ssr-nuxt-deploy
            ls -la
            git pull
            node -v
